### ISSUE TITLE
`Page` 接口改进

### ISSUE THREAD

**Issue by jiadesen** [emosheeep/vite-plugin-virtual-mpa#10]
实际使用中感觉有点奇怪

<img width="572" alt="image" src="https://user-images.githubusercontent.com/22772994/210930547-605bd60e-348e-4202-8fed-637ea32923c7.png">

**Comment by emosheeep** [comment]
这个Page的几个参数是有类型限制的，如果直接用就失去了限制。一开始也没想到大家好像习惯单独写这个配置，目前想到可能比较好点的方式就是提供一个 `createPages` 的方法用来创建 `Pages`了，然后这个接口可以考虑提供一个默认值。

**Comment by jiadesen** [comment]
这毕竟只是个配置项，没必要，要不这么操作，给个默认类型，简单粗暴...

<img width="405" alt="image" src="https://user-images.githubusercontent.com/22772994/211011550-ec5404fe-5acd-40fd-ab7e-43e8c4fbf1e4.png">

**Comment by jiadesen** [comment]
哈哈哈，大哥想搞的完美肯定是支持啦😁

**Comment by emosheeep** [comment]
1.4.0新增了createPages函数，可以试下哈
