### ISSUE TITLE
使用 `cypress` 进行自动化测试时，跨入口跳转动作未正确响应，导致测试无法进行

### ISSUE THREAD

**Issue by jiadesen** [emosheeep/vite-plugin-virtual-mpa#12]
涉及跨页面（入口）的跳转动作，页面始终不能正确 load，导致页面响应超时，测试失败

![image](https://user-images.githubusercontent.com/22772994/211247541-2c6e4e0c-8ac2-4f3a-9cd4-e279c624041e.png)

**Comment by jiadesen** [comment]
使用 vite4 原生支持的多入口没有该问题

**Comment by emosheeep** [comment]
能整个demo吗，我平时没有相关使用场景，不好排查

**Comment by jiadesen** [comment]
稍等

**Comment by emosheeep** [comment]
不着急，我周内要上班没空搞，要搞也周末了，或者你有时间也可以先看看，感觉你也挺上道的呀hhh

**Comment by jiadesen** [comment]
[https://github.com/jiadesen/vite-plugin-virtual-mpa/tree/demo_cypress_0109](url)

**Comment by jiadesen** [comment]
我试着搞一搞吧😴
