### ISSUE TITLE
`createPages` 返回值类型导致添加额外入口时报错

### ISSUE THREAD

**Issue by jiadesen** [emosheeep/vite-plugin-virtual-mpa#14]
我一直觉得类型设计的太复杂了...不利于灵活使用

<img width="1372" alt="image" src="https://user-images.githubusercontent.com/22772994/211461188-e00c6d23-fc30-4721-bf69-bd4a4b992d9d.png">

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/22772994/211460543-b9486ad8-64df-4807-a5e8-669d6361b977.png">

**Comment by emosheeep** [comment]
该有的限制还是要有的，写类型就是为了能做一些静态分析，如果大家都按照规定的方式写的话可能奇怪的bug也会少很多，就不用运行时检查太多东西了

**Comment by emosheeep** [comment]
看上去这块由于泛型的存在确实不支持这样使用，如果想...展开，可以给那个字面量对象也包一层 createPages 函数，如

```js
createMpaPlugin({
  pages: [
    ...createPages({
      name: 'keystone',
      entry: '/src/modules/keystone/main.js',
      data: { title: '资产库 - 基石' },
    }),
    ...createPages({
      name: 'list',
      entry: '/src/modules/list/main.js',
      data: { title: '资产库 - 名单' },
    }),
  ],
}),
```

**Comment by jiadesen** [comment]
这么搞复杂了，指定一下 `createPages` 的返回值类型为 `Page[]` 我觉得也可以

**Comment by emosheeep** [comment]
这样是不行的，会导致原本的字面量失去类型提示，不妥

**Comment by jiadesen** [comment]
> 会导致原本的字面量失去类型提示

我认为这个不重要，要这个提示有啥用...

**Comment by emosheeep** [comment]
我理解，不需要的话可以直接 ts-ignore

**Comment by jiadesen** [comment]
算了，我还是直接这么用吧...

```
import type { Page } from "vite-plugin-virtual-mpa";

const pages: Page[] = [...];
```
