### ISSUE TITLE
请问如何在多页面中使用history路由?

### ISSUE THREAD

**Issue by xxxxj-up** [emosheeep/vite-plugin-virtual-mpa#23]
感谢大佬所作插件,不过在使用时遇到了路由的问题,想咨询一下如何多页面中使用history路由?小弟谢谢了

**Comment by emosheeep** [comment]
你给个demo描述下你想要的效果呗，现在啥都没有不好解释...

**Comment by xxxxj-up** [comment]
代码在此
https://e.coding.net/xxxxj-up/vite-template/vite-template.git
项目是通过
'''
pnpm create vue@latest
'''
创建的,引入了一些插件.
目的就是多页面中使用history路由
url访问长这样的: 
'''
http://localhost:5173/index/about
'''
不带#号(带#号的hash模式)
小弟刚做前端项目没多久,还请大佬海涵

**Comment by emosheeep** [comment]
🫣🫣你这个地址是企业地址，我无法访问的，你把那个配置文件贴出来就可以了

**Comment by xxxxj-up** [comment]
https://xxxxj-up.coding.net/public/vite-template/vite-template/git/files
大佬再试试

**Comment by emosheeep** [comment]
文档里的配置，改一下就好了，from是路径
```
rewrites: [
  {
    from: /index|backstage/,
    to: (ctx) => 对应html文件的路径
],
```

**Comment by xxxxj-up** [comment]
哇,谢谢大佬

**Comment by xxxxj-up** [comment]
大佬,我还有一个小小的问题:
from中如何自动匹配,如
http://localhost:5173/backstage/about 中的 about 部分和 http://localhost:5173/backstage/ 中的 / 部分,比如如果增加新的路由就需要更多的手动配置from,且无法匹配 / 部分

**Comment by xxxxj-up** [comment]
大佬,我还有一个小小的问题:
from中如何自动匹配,如
http://localhost:5173/backstage/about 中的 about 部分和 http://localhost:5173/backstage/ 中的 / 部分,比如如果增加新的路由就需要更多的手动配置from,且无法匹配 / 部分

**Comment by emosheeep** [comment]
你想要自动匹配你就要按照一定的规律来配置目录结构呀. README 里面已经说明了呀，你按照示例里面写的结构去写，就会生成一份默认的配置，再不行你就用数组 map 一份配置写上去就好了

```js
rewrites: pages.map(item => ({
  from: new RegExp(`/${item.name}`)
  to: (ctx) => 对应html文件的路径
}))
```

**Comment by xxxxj-up** [comment]
谢谢大佬的再次指点
我已经将代码再次提交在了原仓库,不过有一些小小的bug和建议在这里列出来:
路由问题:
http://localhost:5173/index/
http://localhost:5173/index/about
因为路由与入口配置冲突问题无法获取应有结果,可不修复
http://localhost:5173/backstage/about
因为路由配置或未知问题无法获取应有结果

重定向问题:
每一个rewrite的from为以配置顺序,在url中倒序匹配,即

      rewrites: [
        {
          from: new RegExp(normalizePath(`/(about)`)),
          to: (ctx) => normalizePath(`/pages/index.html/${ctx.match[1]}`),
        },
        {
          from: new RegExp(normalizePath(`/(backstage)/(about)`)),
          to: (ctx) =>
            normalizePath(`/pages/${ctx.match[1]}.html/${ctx.match[2]}`),
        },
      ],

如此配置

http://localhost:5173/backstage/about 会重定向至 /pages/index.html/about 而非 /pages/backstage.html/about

即 /backstage/about 中先匹配 about 再匹配 backstage .按照配置顺序,使用第一个rewrite

若为 connect-history-api-fallback 包的问题,我会在那里报告issues,建议在文档中提醒

一些其他建议,相较而言可解决不必要,我会后续提交在仓库中

再次感谢大佬答疑

**Comment by emosheeep** [comment]
我觉得你把问题复杂化了，我跑了你的项目，不配置 rewrites 的情况下，我看了重定向的log是没有问题的。
<img width="556" alt="截屏2023-02-05 00 26 40" src="https://user-images.githubusercontent.com/31957758/216778458-211315a7-9cef-4d6b-8edc-ee5b160e748c.png">
你可能没有搞清楚的概念是什么是 History Fallback，我们的重定向只负责定位到对应的html文件，比如这里的
```
/index/about to /pages/index.html
```
是没有问题的，HistoryFallback 负责把 /index/about 这个路由下的入口文件定位到目录下的 /pages/index.html，剩下的这个 /about 那是前端的 vue-router 负责的事情，和 HistoryFallback 是两回事。你可以去了解下 **HistoryFallback** 和 **前端路由** 这两个概念，了解了应该就知道怎么配置了
