### ISSUE TITLE
打包编译输出能否分离开？

### ISSUE THREAD

**Issue by hxzAugustinus** [emosheeep/vite-plugin-virtual-mpa#24]
![image](https://user-images.githubusercontent.com/14306029/216946557-2ea0ed5c-abf4-4e53-b0e3-fe259d9c2168.png)

目前编译不同入口的静态文件都放在一个assets中；

能否实现如下结构的

----dist
--------demo1
------------demo1.html
------------demo1assets
--------demo2
------------demo2.html
------------demo2assets

让每个入口的编译结果隔离 ，目的是 如果只有一个入口的编译结果有变更尽可能小范围的部署变更文件，而不是每次都全部覆盖部署

**Comment by emosheeep** [comment]
emm好像vite没有提供这个能力诶，要搞的话可能还得研究下，有兴趣PR不

**Comment by hxzAugustinus** [comment]
有时间我也研究一下，如果有结果的会pr的

**Comment by emosheeep** [comment]
大致看了下好像并没有很好的方式来做，无非是通过配置 rollup.output 里面的 chunkFileNames entryFileNames assetFileNames 来实现目录定制，但是我们好像没办法简单的判断一个文件到底属于哪个entry里面。

我理解，部署的话，有 hash 变化，并不会覆盖文件呀。如果实在想实现的话，有个简便的方式就是用三份配置构建三次即可。

**Comment by hxzAugustinus** [comment]
这个估计不行，  我试验发现，如果不同入口有引用相同组件 或则 相同图片 等资源 ，打包时会生成公共bundle ，还是无法彻底隔离 ，至少需要一个公共的模块部分 。
主要我自己也没考虑清楚我自己这边的业务 是使用 mpa 还是  pnpm  monorepo  合适   。
