### ISSUE TITLE
禁止插件警告信息

### ISSUE THREAD

**Issue by usercao** [emosheeep/vite-plugin-virtual-mpa#28]
![image](https://user-images.githubusercontent.com/13760476/223379758-609b1222-9b12-4fbc-b385-93e1f180a422.png)

在使用本插件时一直提示警告信息，请问有什么办法可以关闭这个提示呢？我的配置如下:

```js
    createMpaPlugin({
      verbose: false,
      template: 'public/index.html',
      pages: [{ name: 'index', filename: 'index.html' }],
      rewrites: [{ to: () => normalizePath('/public/index.html') }],
    }),
```

如果不写`rewrites`没有警告信息，但是刷新之后会导致路由404。

**Comment by emosheeep** [comment]
换一下模板路径，不要放到public目录下，这个目录会被vite当做静态目录代理。或者你就
```js
// vite.config
{
  publicDir: false
}
```

**Comment by usercao** [comment]
感谢，我就是希望把`index.html`放回到`public `目录下，为此几乎找遍了所有插件，只有此插件是最快速的，但是到最后还是开始报警告信息非常难受，这个改动只是个人喜好。

**Comment by emosheeep** [comment]
理解，那个信息是vite报的，不是插件报的

**Comment by usercao** [comment]
```js
{
  publicDir: false
}
```

请问这个改动会对build等造成什么影响吗？我刚才大概看了一下官方文档，但是他写的比较简略

**Comment by emosheeep** [comment]
不会，但是会对开发造成影响，如果你目录下有文件并且需要通过根路径访问的话

**Comment by usercao** [comment]
感谢回复，我已发现`favicon.ico`无法访问了，我搜索试试如何解决🙏

**Comment by emosheeep** [comment]
你把html放出去就好了，或者重新开个目录叫做static然后配置成publicDir就好了

**Comment by usercao** [comment]
唉，就是强迫症犯了，我也看了阿里的`icejs`框架，插件代码也是这样开虚拟入口(index在public中)但是不会报警告，我再看看吧谢谢

**Comment by usercao** [comment]
找到原因了，经过测试本插件在Vite`4.1`为分水岭，之前的版本配置如下时
```js
      createMpaPlugin({
        verbose: false,
        pages: [
          {
            name: 'index',
            filename: 'index.html',
            template: 'public/index.html',
          },
        ],
      }),
```
可以满足`修改应用入口`需求，并且Vite不会报警告。

但在`4.1`及之后的版本中上述写法会导致页面刷新后丢失路由，只能修改为
```js
    createMpaPlugin({
      verbose: false,
      template: 'public/index.html',
      pages: [{ name: 'index', filename: 'index.html' }],
      rewrites: [
        { from: /.*/, to: '/public/index.html' },
      ],
    }),
```
但是如此一来页面刷新或者热重载会不停的发出警告，是否插件可以跟进下`4.1`后续版本更新呢？
我查看了Vite`4.1`及其以后的更新，猜测有可能是`Rollup`升级导致了这个问题。

**Comment by emosheeep** [comment]
你给个最小复现demo吧，我周末看看
