### ISSUE TITLE
请问插件支持自动根据给定目录解析页面吗？

### ISSUE THREAD

**Issue by angus96** [emosheeep/vite-plugin-virtual-mpa#29]
我目前是vite-plugin-mpa用户，使用方式是通过插件的默认配置解析`src/pages`, 自动解析入口

看README说支持了全部的vite-plugin-mpa功能，但是好像pages属性必须要手动配置，好像不支持通过给定目录直接解析的，希望作者大大解惑

**Comment by emosheeep** [comment]
这个功能没有内置，目前还是通过手动配置的，通过手动配置的好处主要是，我们可以自己控制生成文件的路径。那个插件就是不支持自定义产物路径，不支持多个配置共用一份模板

**Comment by angus96** [comment]
> 那个插件就是不支持自定义产物路径

我期望的使用场景是这样的：如果说我有对某个页面去自定义产物路径，那么针对这个页面我可以做单独配置，但是其他页面对我来说基本都是相似的（这里相似指的是：模板一致，入口路径相似）。对这种相似的页面，我不太想做重复的工作，并且也希望支持在创建一个新页面后，不需要在config里手动添加

**Comment by emosheeep** [comment]
这种倒也合理，不过我目前工作比较忙，能分在上面的精力有限，后续我可能抽空有时间了可以搞一下，如果你着急的话，也可以提个 PR

**Comment by emosheeep** [comment]
1.8.0 已经发布，新增了 `scanOptions`
