### ISSUE TITLE
BUG: Cross-platform path parsing error, can not recognize backslash('\') on windows when using `scanOptions`.

### ISSUE THREAD

**Issue by Xli33** [emosheeep/vite-plugin-virtual-mpa#41]
配置
```
scanOptions: {
          scanDirs: 'src/pages',
          entryFile: 'main.ts',
          filename: (name) => `pages/${name}.html`
        }
```
然后无论开发还是打包都会报错
**`Entry must be an absolute path relative to the project root, received '\src\pages\xxx\main.ts'`**

![image](https://user-images.githubusercontent.com/28592778/235942599-bd472603-1cbb-4231-b779-1234e793a7aa.png)

应该是因为configInit里面只判断了 `/` ，但windows上用的 `\` 所以 path.join 返回路径里的分隔符是 `\` ，从而导致匹配不到报错

![image](https://user-images.githubusercontent.com/28592778/235939743-5e5cf377-b9a2-4567-ba85-e57aef0581e4.png)

**Comment by emosheeep** [comment]
刚刚发了 1.8.3-beta.0 版本，你可以试试看有没有问题，没问题的话我就发正式版了

**Comment by Xli33** [comment]
> 刚刚发了 1.8.3-beta.0 版本，你可以试试看有没有问题，没问题的话我就发正式版了

好的，刚试了ok，多谢大佬，辛苦大佬♪(･ω･)ﾉ
