### ISSUE TITLE
Windows上当`base`为`''`或`'./'`时，打包后HTML里的资源路径会包含项目所在的目录

### ISSUE THREAD

**Issue by Xli33** [emosheeep/vite-plugin-virtual-mpa#43]
可以在Windows上使用这个[demo](https://stackblitz.com/edit/vitejs-vite-upxyey?file=vite.config.js,dist%2Findex.html&terminal=dev)复现，只用了vite和插件

因为不能限制base为固定的名字，所以想着用 `''` / `./` 了，开发时没问题，然鹅打包后(⊙o⊙)…

**没用插件时的配置**
```
export default {
  base: '', // './'也一样
};
```
打包后资源的路径是以 `./` 开头的，这时是对的

![image](https://github.com/emosheeep/vite-plugin-virtual-mpa/assets/28592778/2a27a709-7ceb-41e9-9a14-804ea3b189d6)

**但是使用了插件后，生成的路径就会包含项目所在的目录路径**
```
export default {
  base: '',
  plugins: [
    createMpaPlugin({
      pages: [
        {
          name: 'index'
        }
      ]
    }),
  ],
};
```
![image](https://github.com/emosheeep/vite-plugin-virtual-mpa/assets/28592778/c97c5752-9f87-4e4b-a3ab-812104de673d)

也下载了仓库里的example试过，但只要把base改成 '' 或 './' 后结果都是一样了，甚至文件夹名字太长还会被截断 (ಥ﹏ಥ)

**Comment by emosheeep** [comment]
可以看看你的配置吗

**Comment by Xli33** [comment]
> 可以看看你的配置吗

不好意思，忘了说上面的截图就是在本机上用那个demo弄的，配置是这样的

```
import { createMpaPlugin } from 'vite-plugin-virtual-mpa';

export default {
  base: '',
  plugins: [
    createMpaPlugin({
      pages: [
        {
          name: 'index'
        }
      ]
    }),
  ],
};
```

**Comment by Xli33** [comment]
> 我有空借个windows电脑看下，现在在上班没法看，你如果着急或者有空，可以提个PR，等我的话，我是不能保证什么时候有时间的

么事，这个不急，后面先用其他方式曲线救国了
P.S 抱歉打扰工作、、(。・＿・。)ﾉ

**Comment by emosheeep** [comment]
我今天借到了一个windows 看了下这个问题，我感觉可能是 vite 的问题，我在 windows 系统中复现了相关问题，而 MacOS 一切正常，所以我去提了一个 issue，等等后续再看。
https://github.com/vitejs/vite/issues/13406

**Comment by Xli33** [comment]
> 我今天借到了一台 windows 看了下这个，我感觉可能是 vite 的问题，我在 windows 系统中复现了一个最小 demo，但同样的 demo 在 MacOS 上一切正常，所以我去提了一个 [vitejs/vite#13406](https://github.com/vitejs/vite/issues/13406) ，等等后续再看。

好哒，大佬辛苦了(･ω･)ﾉ

**Comment by yokiyokiyoki** [comment]
应该是这个issue的修复影响了最新版本[vite:resolve] id.startsWith is not a function
