### ISSUE TITLE
Support for disabling rewrites

### ISSUE THREAD

**Issue by renataogarcia** [emosheeep/vite-plugin-virtual-mpa#44]
I'm using the plugin and don't require the rewrites, however I'm proxying /api and the default rewrite ends up rewriting it. I can workaround it by writing a bypass rewrite as:
`rewrites: [{from: /.*/, to: ({parsedUrl, request}) => request.url}],`

but would be nice to be able to do something like:
`rewrites: false`

**Comment by emosheeep** [comment]
It sounds like a reasonable feature, I'll implement it when I'm free, also you could file an PR if you're in emergency.

**Comment by emosheeep** [comment]
The latest version 1.9.0 has fixed this problem.

**Comment by renataogarcia** [comment]
Thanks! It works like a charm!
