### ISSUE TITLE
1.9.1下报错[vite:resolve] id.startsWith is not a function

### ISSUE THREAD

**Issue by yokiyokiyoki** [emosheeep/vite-plugin-virtual-mpa#47]
在vite 2.9.16下报错
1.9.0无问题

![image](https://github.com/emosheeep/vite-plugin-virtual-mpa/assets/20388810/5756804a-f3a9-43fa-a17d-6717927fd337)

**Comment by emosheeep** [comment]
最新版 vite 会报错不

**Comment by yokiyokiyoki** [comment]
![image](https://github.com/emosheeep/vite-plugin-virtual-mpa/assets/20388810/5844c315-5bf4-4f5f-a4b5-69903ff12002)
目测这里要判断下

**Comment by yokiyokiyoki** [comment]
> 

是说vite4?不太好升最新版本，有依赖的其他插件，是要vite2.

**Comment by emosheeep** [comment]
理论上来说这里的id不会为空，可能vite2.x对应的Rollup2.x有一些不同。另外我在mac系统上尝试复现没有发现你说的问题，是否能提供一个复现demo呢，有可能是window系统特有的bug也说不定，就像上个issue
