### ISSUE TITLE
如何添加自定义的meta

### ISSUE THREAD

**Issue by sendking** [emosheeep/vite-plugin-virtual-mpa#5]
期望：
createMpaPlugin({
        pages: [
          {
            name: 'lucky-draw',
            filename: 'lucky-draw/index.html',
            entry: `/src/pages/lucky-draw/main.ts`,
            data: {
              title: '抽奖活动123',
              meta: 'width=device-width,initial-scale=1.0,user-scalable=no,minimum-scale=1,maximum-scale=1',
            },
          },
        ],
      })
通过添加meta标签注入到模版中

**Comment by emosheeep** [comment]
模板文件支持使用ejs语法，可以在这里放数据，然后在模板里面渲染
