### ISSUE TITLE
HTML fallback not working with "root" option

### ISSUE THREAD

**Issue by renataogarcia** [emosheeep/vite-plugin-virtual-mpa#50]
When using 'root' option in the config the html fallback won't find the page, unless the 'root' folder is included in the URL.
```js
{
...
root: "src",
}
```
URL:
http://localhost/test/index.html => Doesn't work

http://localhost/src/test/index.html => Works fine!

I've patched locally [this line](https://github.com/emosheeep/vite-plugin-virtual-mpa/blob/4903fb087b8ffb758f381c4374918994823bf2cd/workspaces/plugin/src/plugin.ts#L284) and got it working by `path.resolve` and the `config.root`.

**Comment by emosheeep** [comment]
🤔It seems you're right, but I'm not free now because I have to work, you could file an PR to fix it if you're in emergency. But
