### ISSUE TITLE
Vite 5 - 404 on scripts when using base

### ISSUE THREAD

**Issue by renataogarcia** [emosheeep/vite-plugin-virtual-mpa#61]
When I upgrade to Vite 5, I get a 404 on scripts if `base` option is in use.

I've done some investigation, and found that what is causing the issue is likely to be this change on vite https://github.com/vitejs/vite/pull/5657.

After the plugin calls `transformHtml`  it changes:
```html
<script type="module">
      console.log("TESTING")
</script>
```
into:
```html
<script type="module" src="/@id/__x00__/myBase/test.html?html-proxy&index=0.js" />
```
This used to work before 5657, but now is no longer supported. Vite expects it to have the base in the url as below, otherwise it fails with 404:

```html
<script type="module" src="/myBase/@id/__x00__/myBase/test.html?html-proxy&index=0.js" />
```

I've tested without using the template and it works fine as it resolves to:
```html
<script type="module" src="/myBase/test.html?html-proxy&index=0.js" />
```
I've done a workaround to replace all ".@id/__x00__/" and prepend the base and it seems to work fine.

However, I'm not sure if this is a Vite issue, or a issue with the plugin, whether it is calling `transformHtml` with some missing options or Vite expects it to adjust the module url.

Please let me know your thoughts.

**Comment by emosheeep** [comment]
This plugin only handles html files you've configured in pages option, unmatched paths will be `next()` directly and handled by vite. 🤔

**Comment by renataogarcia** [comment]
Sorry, I wasn't very clear, but the <script> tag is inside the .html files defined in option.

**Comment by emosheeep** [comment]
Did you mean the `transformHtml` provided by the plugin not the `transformIndexHtml` ( vite's plugin api)?

**Comment by renataogarcia** [comment]
The later, `transformIndexHtml`

**Comment by emosheeep** [comment]
> This plugin only handles html files you've configured in pages option, unmatched paths will be `next()` directly and handled by vite. 🤔

Maybe it was relevant about the rewrite rules or proxy config, I guess 🤔

**Comment by renataogarcia** [comment]
I have rewrite rules disabled. I also tried enabling it to see if it would make a difference but it didn't.

The build output works fine and preview too, which to me, suggests that the change introduced in 5657 would also have to cater for virtual modules. I'll try to experiment a bit and see if that could be the case.

**Comment by emosheeep** [comment]
Thanks a lot, I'm in Spring Festival and busy now, don't have much time on here.

**Comment by emosheeep** [comment]
It seems this problem has been fixed in vite@6, and the issue has closed.
