### ISSUE TITLE
引入插件，vscode报警告

### ISSUE THREAD

**Issue by hopkinson** [emosheeep/vite-plugin-virtual-mpa#65]
在vite.config.ts引入该插件，报错..是不是vite5的问题

没有与此调用匹配的重载。
  最后一个重载给出了以下错误。
    不能将类型“Plugin<any>[]”分配给类型“PluginOption”。
      不能将类型“Plugin<any>[]”分配给类型“PluginOption[]”。
        不能将类型“Plugin<any>”分配给类型“PluginOption”。

**Comment by emosheeep** [comment]
问题的根源是插件内部引用的vite 版本和你外面的 vite 版本不一样，你把他们统一了就行了
