### ISSUE TITLE
no <script> tag for entry js after build

### ISSUE THREAD

**Issue by slbb** [emosheeep/vite-plugin-virtual-mpa#66]
After building, all the `.html` files generated by the plugin are missing the `<script>` tag for entry script. 
It happens after updating vite-plugin-virtual-mpa (1.10.1) and vite (5.1.3). I'm not sure which is the cause.
I've tried it in the example project of this repo and it reproduces the bug as well.

**Comment by emosheeep** [comment]
Sorry I can't get the problem, can you provide some code or snapshots?

**Comment by slbb** [comment]
After `npm run build`:

### Expected Behavior
1. `dist/assets/index-<hash>.js` got generated
2. `dist/index.html` got generated
3. there is a `<script src="./assets/index-<hash>.js"></script>` tag links to the `assets/index-<hash>.js` file in `dist/index.html` 

### Issue
1 & 2 is done. But missing 3, which means there is **no** `<script src="./assets/index-<hash>.js"></script>` tag links to the `assets/index-<hash>.js` file.

### Reproduce Issue
```bash
git clone https://github.com/emosheeep/vite-plugin-virtual-mpa
cd vite-plugin-virtual-map/example
npm i
npm run build
```

### Version
vite-plugin-virtual-mpa@1.10.1
vite@5.1.3

By the way, it works well with vite@4.5.3. The issue seems related to vite's recent changes.

**Comment by emosheeep** [comment]
I try to run dev mode and everything runs well，it seems a build error only 🤔.

**Comment by emosheeep** [comment]
https://github.com/emosheeep/vite-plugin-virtual-mpa/issues/67

**Comment by emosheeep** [comment]
<img width="1046" alt="image" src="https://github.com/emosheeep/vite-plugin-virtual-mpa/assets/31957758/58f15bcc-0aeb-4272-91b1-416f86ad437a">

This is the script tag in demo project

```html
<script type="module" crossorigin src="/assets/apple-Oo8wSu7i.js"></script>
```

**Comment by slbb** [comment]
Seems like it's a Windows specific problem. I create a test [repo](https://github.com/slbb/test-mpa/) and build using github workflow. When it runs on ubuntu it works fine. Combined with that fact that vite4 works fine too, so maybe vite5 use some new feature of nodejs which nodejs cannot handle well under Windows.

**Comment by emosheeep** [comment]
For now,have you tried to start with slash？

**Comment by slbb** [comment]
> For now,have you tried to start with slash？

Sorry, I don't get it. Where should I use slash?

BTW, I tried to debug the build process and found that [code here](https://github.com/emosheeep/vite-plugin-virtual-mpa/blob/f16cea2de4423ec50711d241faa17046f2b9a51c/src/plugin.ts#L217) does return the right html string with `<script>` tag, but the final output is still missing that tag. So weird🤔 
To find out the cause need a deeper dive into the code of vite 5 or even rollupjs.

**Comment by emosheeep** [comment]
Sorry I found you used scanOptions, it should be handled internally by the plugin. Maybe you can reference this issue in vite repo to find some help🙏.

**Comment by slbb** [comment]
Thank you very much.
