### ISSUE TITLE
Vue project is not including asset URLs in build output html files

### ISSUE THREAD

**Issue by shivamrawal19** [emosheeep/vite-plugin-virtual-mpa#68]
I have created a detailed StackOverflow question for this, it is here: https://stackoverflow.com/questions/78192074/combination-of-latest-versions-of-vite-vue-vitejs-plugin-vue-and-vite-plugin

( PS I am not sure if it is related to this library or some other dependency, do guide me if that's the case )

Thank you

**Comment by emosheeep** [comment]
Could you please provide a minimal reproduction?

**Comment by emosheeep** [comment]
Well, I missed your [repo](https://github.com/shivamrawal19/testmpa), I'll take a look when I'm free.

**Comment by gillesgros** [comment]
Any news ?
I ran onto the same problem

**Comment by shivamrawal19** [comment]
oh, based on your hint, I updated the vite from "5.0.10" to "5.0.13". ( max it works is till 5.0.13 not after that )
But It removed the "1 high severity vulnerability" warning, while generating proper builds.

So the issue remains for the latest versions of packages, but at least for now, `npm audit` is happy with the versions.

**Comment by shivamrawal19** [comment]
oh, based on your hint, I updated the vite from "5.0.10" to "5.0.13". ( max it works is till 5.0.13 not after that )
But It removed the "1 high severity vulnerability" warning, while generating proper builds.

So the issue remains for the latest versions of packages, but at least for now, npm audit is happy with the versions. Thank you @gillesgros 

( sry for the close - reopen thing, I had mistakenly closed it )

**Comment by emosheeep** [comment]
It seems this problem is caused by vite...I'm sure our plugin don't do things about assets.

**Comment by shivamrawal19** [comment]
ok, I have posted an issue on Vite's GitHub page.

**Comment by emosheeep** [comment]
Nice work! Now I'll close this issue, you can re-open it anytime.
