### ISSUE TITLE
Support EJS Extension

### ISSUE THREAD

**Issue by chmmpagne** [emosheeep/vite-plugin-virtual-mpa#73]
For better IDE completion and correctness, it would be nice to be able to name the template file with a `.ejs` extension.
I.e., `index.ejs`.

I believe this would just be a change to the types (`TplStr`) to allow this as well as some documentation updates.

```ts
export type AllowedExtensions = 'ejs' | 'html';
export type TplStr<T extends string> = T extends `/${infer P}`
  ? TplStr<P>
  : T extends `${infer Q}.${AllowedExtensions}`
    ? TplStr<Q>
    : `${T}.${AllowedExtensions}`;
```

It may be even better to not restrict the file extension at all.

**Comment by emosheeep** [comment]
Does it work well without any other logic changes？

**Comment by chmmpagne** [comment]
> Does it work well without any other logic changes？

I haven't done any real testing, but it looked to me like these paths weren't getting any additional attention that would need more changes.

**Comment by chmmpagne** [comment]
The PR needs to be updated to only allow `.html` for filenames; `.ejs` and `.html` for templates.
No logic changes needed from my testing.
