### ISSUE TITLE
Is it possible to config different base url for different page?

### ISSUE THREAD

**Issue by SGAKonata** [emosheeep/vite-plugin-virtual-mpa#75]
For each page in my project may be deployed with different endpoints, so my index should use different base url to get their static resource.

For example, I have two apps ``apple`` and ``banana`` , and two html after build:

```html
<html lang="en">
    <title>apple</title>
     <script type="module" crossorigin src="/static/js/apple.js"></script>
</html>

<html lang="en">
    <title>banana</title>
     <script type="module" crossorigin src="/static/js/banana.js"></script>
</html>
```
They are deployed with address `http://server/apple` and `http://server/banana` seperately. To get  access to their static files, they need to vist `server/{name}/static`, and this is usually config in `vite.config.ts -> base` but it's a global setting. 

Is it possble to achieve my aim thought this plugin?

**Comment by emosheeep** [comment]
Try this `renderBuiltUrl` API → https://vitejs.dev/guide/build.html#advanced-base-options

**Comment by SGAKonata** [comment]
Thanks a lot.  Althought it's still experimental, but it wroks!
Here is my code
```ts
// vite.config.ts
// defineConfig
    experimental: {
        renderBuiltUrl(filename, { hostId, hostType, type }) {
            if (hostType === 'html') {
                const name = hostId.replace(/\.html$/, '')
                return base + name + '/' + filename
            } else {
                return base + filename
            }
        },
    },
```
